### ISSUE TITLE
Currency Widget for iOS

### ISSUE THREAD

**Issue by DAWarner-HFX** [mezhevikin/converter-help#1]
I had a widget for your currency converter on my old phone... now i have the new iPhone but for the life of me I cannot find the Currency widget that I used to use...

**Comment by mezhevikin** [comment]
👋 Hi @DAWarner-HFX.
Unfortunately, Apple deprecated the old interactive widgets in iOS 14.
And the new home screen widgets can't be interactive.

**Comment by DAWarner-HFX** [comment]
Hi back. I seem to have it working. The issue seems to be the selected
currencies. Is there a way to sort the currencies in the app to have my
favourite at the top of the list?

**Comment by mezhevikin** [comment]
I am sorry. I thought you about the old interactive widget.
Yes. Exchange rates widget works fine.

Change currencies in widget - https://github.com/mezhevikin/converter-help#change-widget
