### ISSUE TITLE
pls contact with me to return my pay

### ISSUE THREAD

**Issue by xingbxinga** [mezhevikin/converter-help#2]
I have hidden the problem of deduction. I did not use your service and deducted the fee. Please return my fee. Please contact me chenyu_877@163.com
 隐藏扣费问题，没有使用到你的服务而扣费，请归还我的费用。请联系我chenyu_877@163.com

**Comment by mezhevikin** [comment]
@xingbxinga
 https://support.apple.com/en-us/HT204084 - Refund for AppStore.
https://support.google.com/googleplay/workflow/9813244?hl=en - Refund for Google Play
